name: location_reminder
description: A location-based reminder app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  flutter_local_notifications: ^13.0.0
  background_fetch: ^1.1.6
  shared_preferences: ^2.1.0
  provider: ^6.0.5
  flutter_background_service: ^2.4.6
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true